version: "3.8"

services:
  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./Database/data:/var/lib/postgresql/data
    networks:
      - db-network
    restart: unless-stopped

  backend:
    build:
      context: ./simpleapi
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - database
    networks:
      - db-network
      - front-network
    restart: on-failure

  httpd:
    build:
      context: ./http-server
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - front-network
    restart: unless-stopped

networks:
  db-network:
    driver: bridge
  front-network:
    driver: bridge

volumes:
  db-data:
    driver: local
