services:
  database:
    build: ./Database
    env_file:
      - .env
    volumes:
      - ./Database/data:/var/lib/postgresql/data
    networks:
      - db-network
    restart: on-failure:3

  backend:
    build: ./simpleapi
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - db-network
      - front-network
    restart: on-failure:3

  httpd:
    build: ./http-server
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - front-network
    restart: on-failure:3

networks:
  db-network:
    driver: bridge
  front-network:
    driver: bridge

volumes:
  db-data:
    driver: local
