---
# tasks file for roles/deploy_env
- name: Deploy .env file to remote server
  copy:
    src: ../.env  # car le fichier est dans ansible/.env
    dest: /home/admin/project/.env
    owner: admin
    group: admin
    mode: '0644'


- name: Deploy .env file to remote server
  copy:
    src: ../../../../.env
    dest: /home/admin/project/.env
    owner: admin
    group: admin
    mode: '0644'