name: Deploy to Server

on:
  workflow_run:
    workflows: ["Publish Docker Images"]
    branches:
      - main
    types:
      - completed


jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible & Docker SDK
        run: |
          python -m pip install --upgrade pip
          pip install ansible docker

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Create .env file from secret
        run: |
          mkdir -p /home/admin/project
          echo "${{ secrets.ENV_CONTENT }}" > /home/admin/project/.env
          
      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i ansible/inventories/setup.yml  ansible/playbook.yml 