name: Publish Docker Images

# This workflow publishes Docker images when the "Test Backend" workflow completes successfully on the main branch
on:
  workflow_run:
    workflows: ["Test Backend"]
    branches:
      - main
    types:
      - completed

jobs:
  build-and-push-docker-image:
    # Only run if the previous workflow concluded successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the backend Docker image
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-backend:latest

      # Build and push the database Docker image
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-database:latest

      # Build and push the HTTP server Docker image
      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-httpd:latest
