name: Test Backend

# Trigger workflow on push to main or develop branches, and on pull requests
on:
  push:
    branches: 
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4

      # Set up JDK 21 using Temurin distribution
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Build and test the project using Maven
      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml

  sonar-analysis:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4

      # Set up JDK 21 using Temurin distribution
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Cache SonarCloud packages to speed up analysis
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Run SonarCloud analysis with Maven
      - name: Run SonarCloud analysis
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            --file ./simple-api/pom.xml
